const Toy = [
  {
    id: 0,
    title: "Funky Mini Train Friction Engine Toy",
    img: "https://content.jdmagicbox.com/quickquotes/images_main/funkey-kids-toys-09-02-2022-20-271191096-sgc291j5.png",
    price: 1000,
    age: '0-18 months',
    rating: 4.5,
    discount: 10,
    isWished: false,
    category: "Train & Vehicle",
  },
  {
    id: 1,
    title: "LEGO Racer Toy with Racing Driver",
    img: "https://content.jdmagicbox.com/quickquotes/images_main/lego-racer-toy-with-racing-driver-minifigure-race-cars-building-sets-6897-speed-champions-audi-sport-quattro-s1-2190103423-jz9fx1i6.jpg",
    price: 1100,
    age: '18-36 months',
    rating: 4.0,
    discount: 10,
    isWished: false,
    category: "Train & Vehicle",
  },
  {
    id: 2,
    title: "Centy Toys Swift Desire Car",
    img: "https://content.jdmagicbox.com/quickquotes/images_main/centy-toys-kids-toys-31-01-2022-022-270815716-5lk65mlq.jpg",
    rating: 5.0,
    age: '3-5 years',
    price: 260,
    discount: 10,
    isWished: false,
    category: "Train & Vehicle",
  },
  {
    id: 3,
    title: "Thomas Vehicle & Action Toys",
    img: "https://content.jdmagicbox.com/quickquotes/images_main/thomas_vehicle_action_toys_ps_celebration__10039281_0.jpeg",
    rating: 3.5,
    age: '3-5 years',
    price: 450,
    discount: 10,
    isWished: false,
    category: "Train & Vehicle",
  },
  {
    id: 4,
    title: "RC Train Toys",
    img: "https://assetscdn1.paytm.com/images/catalog/product/K/KI/KIDAV-INT-MULTIADIT11370977B5FA622/1564605409468_0..jpg",
    rating: 4.5,
    age: '3-5 years',
    price: 800,
    discount: 10,
    isWished: false,
    category: "Train & Vehicle",
  },
  {
    id: 5,
    title: "Monster Truck",
    img: "https://5.imimg.com/data5/KL/UG/MY-38841484/remote-control-monster-car-toy-500x500.jpg",
    rating: 4.0,
    age: '5-7 years',
    price: 1500,
    discount: 10,
    isWished: false,
    category: "Remote Controlled Toys",
  },
  {
    id: 6,
    title: "Cops Car",
    img: "https://assetscdn1.paytm.com/images/catalog/product/K/KI/KIDPLANET-OF-TOPLAN77595C8726776/1564604633635_1..jpg",
    rating: 4.5,
    age: '5-7 years',
    price: 1600,
    discount: 10,
    isWished: false,
    category: "Remote Controlled Toys",
  },
  {
    id: 7,
    title: "Racing Car",
    img: "https://assetscdn1.paytm.com/images/catalog/product/K/KI/KIDAARAV-REMOTEAARA1018007C13A4410/1564605053457_0..jpg",
    rating: 3.5,
    age: '7-9 years',
    price: 1650,
    discount: 10,
    isWished: false,
    category: "Remote Controlled Toys",
  },
  {
    id: 8,
    title: "racing Car Orange",
    img: "https://rukminim1.flixcart.com/image/416/416/jzpvp8w0/remote-control-toy/h/u/3/racing-car-orange-remote-control-rean-original-imafjz53kbvhwzqp.jpeg?q=70",
    rating: 4.0,
    age: '7-9 years',
    price: 1750,
    discount: 10,
    isWished: false,
    category: "Remote Controlled Toys",
  },
  {
    id: 9,
    title: "Ascetic Remote Control Car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71TVGZnFOdS._AC_UL320_.jpg",
    rating: 3.5,
    age: '9-12 years',
    price: 21000,
    discount: 10,
    isWished: false,
    category: "Remote Controlled Toys",
  },
  {
    id: 10,
    title: "Teddy Bear",
    img: "https://m.media-amazon.com/images/I/71olYvEpf0L._SL1500_.jpg",
    rating: 3.0,
    age: '9-12 years',
    price: 700,
    discount: 10,
    isWished: false,
    category: "Soft Toys",
  },
  {
    id: 11,
    title: "Jam & Honey Cream Teddy Soft Toy",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/712hcbzCx0S._AC_UL320_.jpg",
    rating: 3.5,
    age: '12+ years',
    price: 800,
    discount: 10,
    isWished: false,
    category: "Soft Toys",
  },
  {
    id: 12,
    title: "Jam & Honey Shark Soft Toy",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71RIq0RT3kL._AC_UL320_.jpg",
    rating: 5.0,
    age: '12+ years',
    price: 750,
    discount: 10,
    isWished: false,
    category: "Soft Toys",
  },
  {
    id: 13,
    title: "Webby Soft Animal Plush Elephant Toy",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/711DBUR31bS._AC_UL320_.jpg",
    rating: 3.0,
    age: '5-7 years',
    price: 850,
    discount: 10,
    isWished: false,
    category: "Soft Toys",
  },
  {
    id: 14,
    title: "Babique Plush Soft Toy Cute Animal",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/31VtU8AVV1L._AC_UL320_.jpg",
    rating: 4.5,
    age: '7-9 years',
    price: 890,
    discount: 10,
    isWished: false,
    category: "Soft Toys",
  },
  {
    id: 15,
    title: "NHR MCL Rideon Musical Ride on Car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71-tFJJjfdL._AC_UL320_.jpg",
    rating: 5.0,
    age: '0-18 months',
    price: 1200,
    discount: 10,
    isWished: false,
    category: "Ride On Cars",
  },
  {
    id: 16,
    title: "Dash Monkey Ride on for Kids, Baby Car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71Md89blvSL._AC_UL320_.jpg",
    rating: 3.5,
    age: '0-18 months',
    price: 1250,
    discount: 10,
    isWished: false,
    category: "Ride On Cars",
  },
  {
    id: 17,
    title: "Toyzone Crazy frog deluxe magic car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41hNGahs2mL._AC_UL320_.jpg",
    rating: 4.0,
    age: '18-36 months',
    price: 2500,
    discount: 10,
    isWished: false,
    category: "Ride On Cars",
  },
  {
    id: 18,
    title: "Goyal's Indian Farmer Style Farm Tractor Ride Push Car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/A1+DvALD8aL._AC_UL320_.jpg",
    rating: 5.0,
    age: '18-36 months',
    price: 2400,
    discount: 10,
    isWished: false,
    category: "Ride On Cars",
  },
  {
    id: 19,
    title: "Toy House Benz A Class Rechargeable Battery Car",
    img: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81licKFBnjL._AC_UL320_.jpg",
    rating: 4.5,
    age: '3-5 years',
    price: 2300,
    discount: 10,
    isWished: false,
    category: "Ride On Cars",
  },
];

export default Toy;
